### ISSUE TITLE
Error found: Error: Cannot find module 'webdav'

### ISSUE THREAD

**Issue by JanUrlaub** [SoulOfNoob/MMM-NextCloud-Tasks#6]
On a Raspberry 3, with Raspberry Lite OS .
After installing this module, MagicMirror do not start because of this error.

It seems that webdav is a missing depency for this module.
I installed it and it works fine.
```
npm install webdav
```

```
pi@raspberrypi:~/MagicMirror $ DISPLAY=:0 npm start

> magicmirror@2.16.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[20.08.2021 07:51.33.582] [LOG]   Starting MagicMirror: v2.16.0
[20.08.2021 07:51.33.590] [LOG]   Loading config ...
[20.08.2021 07:51.33.602] [LOG]   Loading module helpers ...
[20.08.2021 07:51.33.765] [LOG]   Initializing new module helper ...
[20.08.2021 07:51.33.767] [LOG]   Module helper loaded: MMM-Fuel
[20.08.2021 07:51.33.771] [LOG]   No helper found for module: MMM-google-route.
[20.08.2021 07:51.33.772] [LOG]   No helper found for module: weather.
[20.08.2021 07:51.33.779] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'webdav'
Require stack:
- /home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[20.08.2021 07:51.33.781] [LOG]   Loading module helpers ...
[20.08.2021 07:51.33.783] [LOG]   Initializing new module helper ...
[20.08.2021 07:51.33.785] [LOG]   Module helper loaded: MMM-Fuel
[20.08.2021 07:51.33.787] [LOG]   No helper found for module: MMM-google-route.
[20.08.2021 07:51.33.789] [LOG]   No helper found for module: weather.
[20.08.2021 07:51.33.792] [ERROR] App threw an error during load
[20.08.2021 07:51.33.796] [ERROR] Error: Cannot find module 'webdav'
Require stack:
- /home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/node_helper.js:9:36)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
[20.08.2021 07:51.33.799] [ERROR] Whoops! There was an uncaught exception...
[20.08.2021 07:51.33.809] [ERROR] Error: Cannot find module 'webdav'
Require stack:

- /home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/node_helper.js:9:36)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-NextCloud-Tasks/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[20.08.2021 07:51.33.813] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[20.08.2021 07:51.33.815] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[20.08.2021 07:51.34.670] [LOG]   Launching application.
```

**Comment by JanUrlaub** [comment]
It was some issues with the sd card. Replaced it, run npm install and i works now :-)
